### PR TITLE
Allow loading libca.so from epicscorelibs if it is installed.

### PR DESCRIPTION
**Pull request by willrogers**
@Araneidae here is one way that it might work.

### CODE REVIEW

**Comment by Araneidae** [comment]
Looks pretty fair to me.  @thomascobb, any idea why travis is failing now?  This appears to be the initial error message:

    $ curl -sSL "http://epics.nsls2.bnl.gov/debian/repo-key.pub" | sudo -E apt-key add -
    gpg: no valid OpenPGP data found.

**Comment by willrogers** [comment]
We can drop Python 2.6, surely.

**Comment by thomascobb** [comment]
I hope so!

**Comment by Araneidae** [comment]
> We can drop Python 2.6, surely.

Not until RHEL6 is gone, I think.

**Pull request merged**
